### ISSUE TITLE
get_url doc inconsistency, and returning empty result

### ISSUE THREAD

**Issue by alberth** [vcstools/vcstools#106]
I found two problems with the "get_url" method (vcstools 0.1.37, ubuntu 14.04)

1) Documentation is inconsistent
2) The method returns empty URLs in some cases.

1:
In vcs_base, it's documented as
````
:returns: The source control url for the path
:rtype: str
````
In all concrete vcs classes, it's documented as
````
:returns: GIT URL of the directory path (output of git info command), or None if it cannot be determined
````
(This one is for GIT, but other vcs-es have similar descriptions. They all add "None" as explicit option for return value.)

Clearly something should be decided here.

2:
In my GIT repository, I use "upstream" rather than "origin" as remote repository. Since vcstools assumes "origin", get_url() fails to find a remote repository, and it returns the empty string.
I wonder whether the method should not return None in this case. An empty string is definitely not a valid GIT URL, so it seems to violate the contract of the above description.

PS For my curiosity, why are string commands used for "run_shell_command" rather than a list, and why is shell=True everywhere I look? Afaik the subprocess module suggests to use a list for a command, and avoid shell=True. The sub-routine also doesn't seem to do proper shell escaping of the command, as suggested in https://docs.python.org/3/library/subprocess.html#security-considerations

**Comment by tkruse** [comment]
Hi, thanks for the comment.

I am pleased that anyone even reads the code documentation. I was not quite expecting that. Indeed None could be added in vcs_base as possible return value of get_url().

Whether the git client should consider another remote than "origin" as the relevant remote is also discussed here: https://github.com/vcstools/wstool/issues/59
Maybe you want to join the discussion there.

The sanitized() function in common.py should protect against injection attempts. It is used in places injection would be possible. I cannot remember well why I decided to write a sanitized function instead of using shlex.quote().
In any case the shell escaping always has to be done by the client invoking a command (I think), as only the client can decide which part is a command, and which part is an argument.

Why we use shell=True is more difficult to explain for me, as I cannot remember well. I remember it was a necessity in several cases, meaning commands would not work as expected without it. But I don't remember the individual issues.

**Comment by alberth** [comment]
While my "upstream" is a bit unfortunate in hindsight, I can see why always picking 'origin' is useful, at least in context of ROS. I can quite easily adapt, probably by adding origin with the same destination as upstream, if git allows it.

**Comment by tkruse** [comment]
Yes, git allows having multiple remotes, also with the same URL. It is also very easy to change and switch remote names, they are just labels in the .git/config file.
