### ISSUE TITLE
urlopen usage does not follow redirects

### ISSUE THREAD

**Issue by tfoote** [vcstools/vcstools#114]
geometry_experimental was renamed to geometry2

The pull request is pending: https://github.com/ros/rosdistro/pull/10926
And in the mean time github is doing redirects which works for browser access and things like wget and git also work correctly.  However the vcstools downloads of the release tarballs is failing due to not following the redirects. https://github.com/ros/geometry2/issues/166

I believe the underlying issue is that our useage of urlopen does not follow the redirects. https://github.com/vcstools/vcstools/blob/master/src/vcstools/common.py

**Comment by tkruse** [comment]
It's a bit difficult to judge since you did not give steps to reproduce, but based on the output of  ros/geometry2#166, I believe there is no bug.

Assuming this .rosinstall file:
```
- tar:
    local-name: geom
    uri: https://github.com/ros-gbp/geometry_experimental-release/archive/release/jade/tf2/0.5.13-0.tar.gz
    version: geometry_experimental-release-release-jade-tf2-0.5.13-0
```

I get this error:
```
[geom] Fetching https://github.com/ros-gbp/geometry_experimental-release/archive/release/jade/tf2/0.5.13-0.tar.gz (version geometry_experimental-release-release-jade-tf2-0.5.13-0) to /home/kruset/work/python/wstool/ws4/geom
ERROR [vcstools] Tarball download unpack failed: u"geometry_experimental-release-release-jade-tf2-0.5.13-0 is not a subdirectory with contents in members [u'geometry2-release-release-jade-tf2-0.5.13-0']"[/vcstools]
Exception caught during install: Error processing 'geom' : [geom] Checkout of https://github.com/ros-gbp/geometry_experimental-release/archive/release/jade/tf2/0.5.13-0.tar.gz version geometry_experimental-release-release-jade-tf2-0.5.13-0 into /home/kruset/work/python/wstool/ws4/geom failed.
```
 but the tar download itself works fine. The problem is that inside the tar, the main folder is `geometry2-release-release-jade-tf2-0.5.13-0`, whereas the version givein in `.rosinstall` is `geometry_experimental-release-release-jade-tf2-0.5.13-0`

My .rosinstall was based on this output:
```
Exception caught during install: Error processing 'geometry_experimental/tf2' : [geometry_experimental/tf2] Checkout of https://github.com/ros-gbp/geometry_experimental-release/archive/release/jade/tf2/0.5.13-0.tar.gz version geometry_experimental-release-release-jade-tf2-0.5.13-0 into /home/johannes/ros_catkin_ws/src/geometry_experimental/tf2 failed.
```

I don't know why the error log in ros/geometry2#166 is shorter than mine, though.

**Comment by tfoote** [comment]
@onjen do you still have a copy of the rosinstall file that failed in https://github.com/ros/geometry2/issues/166 otherwise it looks like this is not reproducible from @tkruse 's testing.

**Comment by tkruse** [comment]
based on @onjen s remark "Yesterday the download worked fine." in  ros/geometry2#166  I assume he used an old rosinstall file from rosinstall_generator having the old version attribute that was not correct anymore after the repo rename.

So basically all users with rosinstall files from before the rename can be affected, because in their rosinstall the version attribute now points to a non-existing version label.

**Comment by onjen** [comment]
This is the old rosinstall file where the error occured:
http://pastebin.com/hnFF1jiF

I generated a new rosinstall file directly before the wstool init.

**Comment by tkruse** [comment]
Hi @onjen,
can you still reproduce the problem? If so, can you paste exactly the commands you run on the command line here, so we can try to reproduce? Both for generating the rosinstall file and for running wstool init.

**Comment by onjen** [comment]
Hey @tkruse,
with a new generated rosinstsall file the problem no longer exists, but you can reproduce it by running `wstool init -j8 src jade-desktop-full-wet.rosinstall
`
with this specific rosinstall file.

**Comment by tkruse** [comment]
Yes, that's what I said earlier, rosinstall files generated before the rename stop working.
There is nothing wstool can do about it. This rosinstall file:
```
- tar:
    local-name: geometry_experimental/tf2
    uri: https://github.com/ros-gbp/geometry_experimental-release/archive/release/jade/tf2/0.5.13-0.tar.gz
    version: geometry_experimental-release-release-jade-tf2-0.5.13-0
```
tells wstool to fetch 0.5.13-0.tar.gz and extract the folder inside called "geometry_experimental-release-release-jade-tf2-0.5.13-0". But the folder inside that tar is named geometry2..., not geometry_experimental, so the rosinstall file has is invalid.

A workaround is to manually fix the version attribute in all affected rosinstall files, even if that is rather clumsy. a sed command like this should work, I think (untested):
```
sed -s 's/geometry_experimental/geometry2/g' xyz.rosinstall
```

A proper fix could be not to redirect in github, but to have independent repositories in github. I suggest closing the issue here and describing the details in ros/geometry2#166

**Comment by tfoote** [comment]
Commented over there in case someone else runs into it and pointed them here.
