### ISSUE TITLE
Why two repos with same name?

### ISSUE THREAD

**Issue by davetcoleman** [vcstools/vcstools#135]
See https://github.com/dirk-thomas/vcstool

Both appear to be actively developed, this is very confusing.

**Comment by wjwwood** [comment]
I recommend filing this issue on that issue tracker, since this is the older repository, and we cannot get rid of this repository because serval of the tools used in ROS 1 tutorials rely on it.

I'll close this because there's nothing the maintainers of this repository can do about it. Feel free to continue the discussion.

**Comment by tkruse** [comment]
It's not 2 repos, it's two different projects. And it is in line with the OSRF approach of duplicating all ROS1 development and maintenance effort for ROS2.

This has been discussed in several places, such as here: https://groups.google.com/forum/#!topic/ros-sig-ng-ros/wwKMRBov-7c
or here: https://github.com/vcstools/wstool/issues/19 (at the bottom)

**Comment by wjwwood** [comment]
> Both appear to be actively developed, this is very confusing.

I too wish the name of `vcstool` was different, I agree that it is confusing.

----

> This has been discussed in several places, such as here: https://groups.google.com/forum/#!topic/ros-sig-ng-ros/wwKMRBov-7c

I think my response from then is still apt:

> > VCS support: wstools vs. vcstool  (seen used here: https://github.com/ros2/examples/wiki )

> Well wstool is really nice for some styles of development (especially for merging complex rosinstall files into existing workspaces and updating versioned copies of items in the workspace), but the stateless style of vcstool is sometimes a better fit for our development. There's no reason you couldn't use wstool to checkout the code for ROS 2. My defense is that I feel I'm using the right tool for the job atm, but that doesn't mean I don't use wstool when creating a single workspace with ros_comm and rviz + their dependencies.

This is still true today. I use both `wstool` (which depends on this repository, `vcstools`) and `vcstool`. Sometimes I like `vcstool` better (as a power user), other times `wstool` is more appropriate (especially for instructions for users at many different skill levels).

----

@davetcoleman if you want to know the history, this is my best summary from memory:

I did some initial prototyping of a script called `vcstool.py`, but after a somewhat heated discussion with @tkruse I conceded that I could just use/extend existing tools (like this repository `vcstools` which is actually just a library, and `rosinstall`), see:

https://groups.google.com/d/msg/ros-sig-buildsystem/VqziwxVnmb0/gxHLg5n_4uwJ

I also tried to explain why I started with a simple script and that I had avoided `vcstools` initially due to it not meeting my immediate needs, but also that I feared breaking things that used `vcstools`.

I decided to not work on it anymore and instead I suggested we organize a meeting to come up with a solution, and if I remember correctly that's were we first discussed `wstool`.
Later @tkruse developed `wstool` as a result.
I can't remember then, but today my opinion is that there is value in both kinds of CLI tool, but at the same time they could have lived in the same repository.

After that @dirk-thomas proceeded with development of `vcstool` and I didn't work on it much, if at all.

----

> It is just as fair to say the name "ROS2" is confusing, since both ROS1 and ROS2 are actively developed, but have nothing to do with each other (And it has been said).

I'm sorry that you feel this way, but this is not the place to reignite this discussion or express your grievances. Summarizing the history, offering links to previous discussions, and offering positive solutions moving forward is fine, but please be kind.

Consider this your warning @tkruse. I will remove any further comments that I deem to be off-topic or mean-spirited. I appreciate your input and contributions on these repositories, but I am not going to tolerate stuff like this.

**Comment by davetcoleman** [comment]
Thanks for all these explanations. However even better would be just to document this so that future users don't have to search closed issues to understand:

https://github.com/vcstools/vcstools/pull/136
https://github.com/dirk-thomas/vcstool/pull/67
