### ISSUE TITLE
vcstools make test fails on our build machines

### ISSUE THREAD

**Issue by tfoote** [vcstools/vcstools#77]
It's in the unicode command line test.  I'm not sure why this fails.  I'm going to try on my own lucid machine. It works fine on travis and my precise machine. 

http://jenkins.willowgarage.com:8080/job/_release-vcstools/1/console

```
A         branches/test_branch
.WARNING [vcstools] No tar subdirectory chosen via the 'version' argument for url: https://code.ros.org/svn/release/download/stacks/exploration/exploration-0.3.0/exploration-0.3.0.tar.bz2[/vcstools]
.......
======================================================================
ERROR: test_shell_command_verbose (test.test_base.BaseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rosbuild/hudson/workspace/_release-vcstools/test/test_base.py", line 76, in test_shell_command_verbose
    run_shell_command("echo %s"%(b'\xc3\xa4'.decode('UTF-8')), shell=True, verbose=True)
  File "/home/rosbuild/hudson/workspace/_release-vcstools/src/vcstools/common.py", line 132, in run_shell_command
    env=env)
  File "/usr/lib/python2.6/subprocess.py", line 633, in __init__
    errread, errwrite)
  File "/usr/lib/python2.6/subprocess.py", line 1139, in _execute_child
    raise child_exception
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 5: ordinal not in range(128)
```

**Comment by cottsay** [comment]
Taking another look at this, it seems that this test is broken whenever Python 2 isn't configured to use something besides ASCII, which is in fact, the default encoding. It appears that Python 2.7 will use the system's `LANG` value to change to unicode, which is why this doesn't repro consistently on workstations vs minimalist build environments.

On RHEL 7, which uses Python 2.7, I have to set `LANG=en_US.UTF-8` to work around the bug. On Fedora, I can use the lighter weight `LANG=C.UTF-8`, but the locale really doesn't matter as long as the encoding is unicode. On RHEL 6, which uses Python 2.6, I know of no simple workaround.

Maybe we should just skip the test if Python isn't configured to use Unicode by default, or maybe we should make the decoding lossy. I'm not sure. I'm really not even sure what the test is designed to look for - the ticket numbers from commits at that time don't appear to index into this repositories issues.

Related to commit 1e49d1c486a363c2aef86276766bda9a382945cc.

**Comment by tkruse** [comment]
I would also be fine with skipping the test for all python2 versions, if that helps.
Possibly running tests with any hack to change the encoding such as described in https://stackoverflow.com/questions/2276200/changing-default-encoding-of-python would also work I guess.

**Comment by dirk-thomas** [comment]
Closing since the repository is about to be archived: see #166.
